### ISSUE TITLE
changes in test resources in sciebo crash tests without pipeline trigger

### ISSUE THREAD

**Issue by veronikarichter** [BIM2SIM/bim2sim#721]
If files are changed in any sciebo resources that are used for testing, pipelines do not notice until next run. If changes in sciebo are done accidentely, the CI won't be able to get the source of the failure. 

We should think about reducing the file sizes that are used for testing and move all the files back to github to ensure pipelines are triggered once files have changed. Also, sciebo may be limited in restoring data.

**Comment by DaJansenGit** [comment]
I would strongly disagree to put the resource files for testing in the bim2sim repository (main repository) for multiple reasons, instead @Cudok and I developed the following approach:
1. create a second github repository for all test resources (and mirror this to gitlab)
2. create a pipeline there that runs on merge request and clones the current `development` (and `main`? but no other branches for simplification) branch and tests the code with the changed test resources

If the pipeline fails not merge is possible -> we will always know when something goes wrong and we will have history of the test resources. A pipeline will look like this:

```
test_Base:
 image: $CI_REGISTRY/environment:development
 stage: test

 script:
   - clone bim2sim repo /bim2sim-coding/  # clone bim2sim coding repository from main repo
   - mv ./* /bim2sim-coding/test/resources  # copy the changed test resources into the bim2sim-coding
   - coverage run -m unittest discover /bim2sim-coding/test  # run tests with changed test resources
   - coverage report -i   # give report
   
```
